### ISSUE TITLE
Calling feature needs a dialing pad

### ISSUE THREAD

**Issue by TriggerDingus** [dino/dino#1397] opened 2023-03-21 17:36 UTC
I'm using Dino on Linux to place a call. The call connects fine but when I'm faced with a phone menu in which I need to select a number for my call to be directed properly, my hands are tied because I can't find a way to bring up a dialing pad within Dino.

**Comment by mar-v-in** [comment] 2023-03-22 15:49
Duplicate of #1198

**Closed by mar-v-in** 2023-03-22 15:49 UTC
