### ISSUE TITLE
Indicate which messages are new in a MUC

### ISSUE THREAD

**Issue by RalfJung** [dino/dino#780] opened 2020-03-18 15:41 UTC
When coming back to a MUC that had new messages, there is no indication of which messages are new and which I have already read. That makes it quite hard to properly follow semi-active MUCs.

**Comment by ericschdt** [comment] 2020-03-19 11:19
See https://github.com/dino/dino/issues/192

**Comment by mar-v-in** [comment] 2020-03-25 18:36
Duplicate of #192

**Closed by mar-v-in** 2020-03-25 18:36 UTC
Labels: duplicate
