### ISSUE TITLE
Add an option to create an muc with muc domain auto detected

### ISSUE THREAD

**Issue by pravi** [dino/dino#1298] opened 2022-10-22 15:00 UTC
Currently the Join channel option does not allow you to create a private or public muc, you can only join an existing muc. In conversations app on android, they offer creating private and public muc with some configuration presets.

Private - needs and invite, jid visible to all participants, notifications on for all messages, and address is randomly generated Public - we can choose the address, jid is visible only to admins, notifications on mention by default.

Edit: muc can be created, but need to know the muc domain which is not standard, each provider use a different muc domain.

**Comment by licaon-kter** [comment] 2022-10-22 15:18
That's not true... just press the lower left plus sign.

FAQ: https://github.com/dino/dino/wiki/Frequently-asked-questions-(FAQ)#how-to-create-a-group-chat

**Comment by pravi** [comment] 2022-10-22 15:23
@licaon-kter for this we should know the domain where the muc is hosted in the server which is not required in conversations, so while this works for tech savvy users, this needs improvement, the muc domain should be auto detected.

**Comment by poVoq** [comment] 2022-10-23 07:05
Instead of auto-detection it could also show a list of known MUC namespaces. There are several XMPP servers that act as "spaces" for MUCs and/or have mutliple MUC components to group MUCs thematically and it wouid be nice if that could be exposed in the UI somehow. I assume this is one of the reasons why the current implementation asks for the muc domain instead of just auto-detecting a local one.

**Comment by fiaxh** [comment] 2022-10-28 10:02
This is a duplicate of #1002.

**Closed by fiaxh** 2022-10-28 10:02 UTC
