### ISSUE TITLE
Conversation stays marked unread even though it's read

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#523] opened 2019-02-13 11:54 UTC
I've been observing this for quite a while not, very sporadically.

I think it happens more often (don't dare to say only) with posts containing images (HTTP Upload) and I believe only in MUCs (but that might because I mostly converse in MUCs).

![screenshot-2019-02-13-11-56-47](https://user-images.githubusercontent.com/853468/52709949-0525d780-2f86-11e9-957d-41be12639b53.png)

Might also be related to the fact that I sent it from another device (as opposed to another person having sent it).

**Comment by fiaxh** [comment] 2019-02-13 13:48
This is a duplicate of #495.

**Closed by fiaxh** 2019-02-13 13:48 UTC
