### ISSUE TITLE
Dino does not inform that a MUC has been deleted

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#1131] opened 2021-10-31 09:59 UTC
Dino 8339d95621530664b8306b8b033976529510ed17

#### Steps to reproduce 

In Conversations on conversations.im

1) Create a (public) MUC
2) Join this MUC in Dino
3) Delete this MUC in Conversations

#### Result

Nothing on Dino's side. The user only notices that no more messages arrive and messages cannot be send.

#### Expected result

Dino shows an (inline) notification that the MUC has been deleted.

**Comment by linkmauve** [comment] 2021-11-04 11:54
This is a duplicate of #1095.

**Closed** 2021-11-04 11:58 UTC
