### ISSUE TITLE
Delete chat from computer and server.

### ISSUE THREAD

**Issue by zookeeper76** [dino/dino#1389] opened 2023-03-15 15:40 UTC
Please consider adding the option to delete chats from both the local machine but also on the users XMPP server.

When you close a chat and remove the JID from Dino, if you retype the same JID and open a new chat, all the previous messages are still present since their is no option to delete the data from the server.

**Comment by licaon-kter** [comment] 2023-03-15 15:48
/duplicate https://github.com/dino/dino/issues/472 for local deletion

There's no deletion from server usually, buuut, if you use OMEMO then the  messages will not appear as you can't decrypt them a second time.

**Comment by mar-v-in** [comment] 2023-03-20 22:03
For server-side deletion this could also be considered a duplicate of #1133 and

**Closed by mar-v-in** 2023-03-20 22:03 UTC
Labels: duplicate
