### ISSUE TITLE
Stream Error: TlsError in GLib: Certificat TLS inacceptable

### ISSUE THREAD

**Issue by ouafnico** [dino/dino#151] opened 2017-09-15 07:11 UTC
Hi
Good job for this soft... but actually I can't use it I got this error on console with my jabber server :

Stream Error: TlsError in GLib: Certificat TLS inacceptable

It use self signed certificate.. any way to add a button to ignore certs errors ?

Thanks

**Comment by fiaxh** [comment] 2017-09-19 22:18
Duplicate of #57.

**Closed by fiaxh** 2017-09-19 22:18 UTC
Labels: duplicate
