### ISSUE TITLE
Preserve the case of the last used nick

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#218] opened 2017-11-23 15:44 UTC
It currently gets lowercased at some point.

**Comment by fiaxh** [comment] 2020-05-07 13:53
I couldn't reproduce this issue back when you opened it. Does this issue still happen for you?

**Comment by fiaxh** [comment] 2020-07-13 15:24
Closing this issue. If you have further information or if you can reproduce this I can reopen the issue though.

**Closed by fiaxh** 2020-07-13 15:24 UTC
Labels: information needed
