### ISSUE TITLE
I would like to use xmpp to make audio and video calls if the server supports it.

### ISSUE THREAD

**Issue by Eragonfr** [dino/dino#409] opened 2018-07-27 10:52 UTC
I want use xmpp and webrtc in dino it's possible?

**Comment by licaon-kter** [comment] 2018-07-27 11:44
Detail your case...

**Comment by Eragonfr** [comment] 2018-07-28 17:09
I would like to use xmpp to make audio and video calls if the server supports it.
Sory for bad english.

**Comment by licaon-kter** [comment] 2018-07-28 19:56
Rename your issue then

**Comment by fiaxh** [comment] 2018-07-29 21:08
Duplicate of #154.

**Closed by fiaxh** 2018-07-29 21:08 UTC
