### ISSUE TITLE
display availability in "start chat" list

### ISSUE THREAD

**Issue by RalfJung** [dino/dino#205] opened 2017-11-07 09:07 UTC
It would be great to see if a contact is online in the "start chat" list of all contacts. I have some contacts in my roster multiple times, and I forgot which account they actively use. If I could see that one of the accounts was online, that would be a good indicator -- whereas right now, I'd have to start conversations with all these accounts just to see if any of them is still being used.

**Comment by fiaxh** [comment] 2017-11-08 19:36
Duplicate of #139.

**Closed by fiaxh** 2017-11-08 19:36 UTC
Labels: duplicate
