### ISSUE TITLE
Display the word "Spam" for moderated messages 

### ISSUE THREAD

**Issue by speedygonzales9** [dino/dino#1404] opened 2023-03-24 18:15 UTC
Dino should have at least partial support for [XEP-0425: Message Moderation](https://xmpp.org/extensions/xep-0425.html). Once a message gets moderated, Dino should change the message body to the word "Spam". I would like to make this a feature request please. 

Thank you

**Comment by fiaxh** [comment] 2023-03-24 18:29
This is a duplicate of #1133.

**Closed by fiaxh** 2023-03-24 18:29 UTC
Labels: duplicate
