### ISSUE TITLE
Can't send image in group chat (No sender/encryptor combination available)

### ISSUE THREAD

**Issue by Elinvention** [dino/dino#727] opened 2020-01-25 16:45 UTC
Whenever I try to send an image on a group chat, I get this error in the terminal:
```
(dino:22236): libdino-WARNING **: 17:35:21.138: file_manager.vala:118: Send file error: No sender/encryptor combination available
```
I tried with OMEMO enabled too (we don't use it in that chat).

The GUI just shows a yellow exclamation mark, next to the send time, which in my opinion is a bit too hidden and subtle and I didn't notice there was a problem. Then if I switch to another chat and come back, it shows the proper error message: "File transfer failed" or whatever it is in English.

I recall this feature was working in previous dino versions, maybe I can try to git bisect it.

**Comment by licaon-kter** [comment] 2020-01-25 16:59
What server? Listed on https://compliance.conversations.im ?

**Comment by Elinvention** [comment] 2020-01-26 19:09
Yes https://compliance.conversations.im/server/elinvention.ovh/. I should have mentioned that I can send images from other clients like Gajim and Conversations.

**Comment by Elinvention** [comment] 2020-01-30 22:10
I was looking at the code, but I can't find `FileSender`'s definition.

**Comment by anjandev** [comment] 2020-02-08 02:58
I had this issue previously and it was caused by extra (bad) omemo keys generated by converse.js. After disabling those keys, I was able to send messages in the group chat again. 

I recently faced this issue again and I went through and disabled keys I didnt use but the problem was not fixed. 

@Elinvention if you want to look into the issue, the line where the error is thrown is here:
https://github.com/dino/dino/blob/master/libdino/src/service/file_manager.vala#L101

**Comment by Elinvention** [comment] 2020-02-08 23:31
Thanks, but I already saw that line. I was wondering where I can find what is a FileSender https://github.com/dino/dino/blob/master/libdino/src/service/file_manager.vala#L80

**Comment by anjandev** [comment] 2020-02-09 05:50
I misunderstood. I found the following using grep:

If the file is being sent over jingle: https://github.com/dino/dino/blob/05561dd677b4098d1a618bcc3e01fc77c5ce19de/libdino/src/service/jingle_file_transfers.vala

If the file is being sent over http (more likely): https://github.com/dino/dino/blob/687ec1a15969a88e00f84b6f45f751c99cc91d92/plugins/http-files/src/file_sender.vala

**Comment by Elinvention** [comment] 2020-02-11 11:02
So, in vala you can avoid defining the superclass FileSender?

However the issue disappeared. Now that I started dino with GDB, I could send images... I also checked without and it works. Something definitely did happen in the past days. 3 days ago I followed your advice about OMEMO keys, but it didn't work. Maybe, yesterday I restarted the server and that did reset something?

**Comment by kmq** [comment] 2020-04-17 17:29
I debugged this a little:

Prosody returns the result of the discoinfo query in multiple `jabber:x:data:x` elements like so:
```
[...]
<{http://jabber.org/protocol/disco#info}:feature {http://jabber.org/protocol/disco#info}:var='vcard-temp' />
    <{jabber:x:data}:x {jabber:x:data}:type='result' {http://www.w3.org/2000/xmlns/}:xmlns='jabber:x:data'>
      [...]
    </{jabber:x:data}:x>
    <{jabber:x:data}:x {jabber:x:data}:type='result' {http://www.w3.org/2000/xmlns/}:xmlns='jabber:x:data'>
      <{jabber:x:data}:field {jabber:x:data}:type='hidden' {jabber:x:data}:var='FORM_TYPE'>
        <{jabber:x:data}:value>
          urn:xmpp:http:upload
        </{jabber:x:data}:value>
      </{jabber:x:data}:field>
      <{jabber:x:data}:field {jabber:x:data}:type='text-single' {jabber:x:data}:var='max-file-size'>
        <{jabber:x:data}:value>
          10485760
        </{jabber:x:data}:value>
      </{jabber:x:data}:field>
    </{jabber:x:data}:x>
  </{http://jabber.org/protocol/disco#info}:query>

```
This is extracted in dino here:

https://github.com/dino/dino/blob/13d3d2aca6f5975bbf16ba56b7cd0c4e2008e936/xmpp-vala/src/module/xep/0363_http_file_upload.vala#L157

`get_deep_subnode` only returns the first result and so the information for the http-upload gets lost.

I created a pull request https://github.com/dino/dino/pull/809

**Comment by Elinvention** [comment] 2020-04-18 18:17
Nice! I compiled latest master and I'll let you know if the issue returns. It's hard to tell because it occurred again a few days ago and mysteriously disappeared the next day...

**Comment by anjandev** [comment] 2020-04-24 08:48
I was running into this bug on dino-0.1 after I rebooted my prosody server today. I decided to compile the latest master from source and the bug disappeared. Thanks @kmq!

**Comment by fiaxh** [comment] 2020-07-13 16:01
kmq's fix has been merged a while ago, so I'm closing this issue.

**Closed by fiaxh** 2020-07-13 16:01 UTC
