### ISSUE TITLE
A correct support of OMEMO: 12 byte for initilization vector (IV)

### ISSUE THREAD

**Issue by Neustradamus** [dino/dino#749] opened 2020-02-16 20:41 UTC
There is a problem in the code:
- https://github.com/xsf/xeps/pull/894

**Comment by mar-v-in** [comment] 2020-02-16 23:01
Duplicate of #265

**Closed by mar-v-in** 2020-02-16 23:01 UTC

**Comment by Neustradamus** [comment] 2020-09-15 23:49
It is now solved:
- https://github.com/dino/dino/commit/cd5b639a826ccafe5741a51f10cc8ca76ebfdd14
- https://github.com/dino/dino/commit/1956f63179c4f3ac3232cc4a2da8046565fad2a1 (https://github.com/dino/dino/issues/909)

**Comment by Neustradamus** [comment] 2020-11-12 23:03
Good news:
- https://github.com/dino/dino/issues/265#issuecomment-726389726
