### ISSUE TITLE
Dino Connection breaks because of TLS socket error

### ISSUE THREAD

**Issue by mightyBroccoli** [dino/dino#163] opened 2017-09-21 12:30 UTC
I am connected to [magicbroccoli.de](//magicbroccoli.de/xmpp). The server is running prosody 0.10 with the latest build. 
* valid 4096 bit LetsEncrypt cert
* connected from a strong wlan connection from my university ( i am sitting right below the ap )
*  [XMPP Rating](https://tls.imirhil.fr/https/magicbroccoli.de)

The errors are in german I try to translate them as close as possible.

[ GERMAN ] ** (dino:18191): CRITICAL **: file /var/abs/local/dino-git/src/dino/xmpp-vala/src/core/stanza_writer.vala: line 10: uncaught error: Fehler beim Schreiben der Daten in den TLS-Socket: Die angegebene Sitzung wurde aus irgendwelchen Gründen ungültig. (g-tls-error-quark, 1)
[ENGLISH] ** (dino:18191): CRITICAL **: file /var/abs/local/dino-git/src/dino/xmpp-vala/src/core/stanza_writer.vala: line 10: uncaught error: Error writing data to the TLS-Socket: The used session is somehow unvalid. (g-tls-error-quark, 1)

[ GERMAN ] ** (dino:18191): CRITICAL **: file /var/abs/local/dino-git/src/dino/xmpp-vala/src/core/stanza_writer.vala: line 21: unexpected error: Fehler beim Schreiben der Daten in den TLS-Socket: Die angegebene Sitzung wurde aus irgendwelchen Gründen ungültig. (g-tls-error-quark, 1)
Stream Error: IOError in GLib: Fehler beim Erhalt von Daten: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
recovering in 3

[ENGLISH] ** (dino:18191): CRITICAL **: file /var/abs/local/dino-git/src/dino/xmpp-vala/src/core/stanza_writer.vala: line 21: unexpected error: Error writing data to the TLS-Socket: the used session is somehow unvailid. (g-tls-error-quark, 1) Stream Error IOError in GLib: Error recieving data: The connection was reset by the peer.

I get the error once an hour which disconnects dino and sometimes does not reconnect it automatically. This sometimes results in message loss.

**Comment by svalo** [comment] 2017-09-21 12:43
I don't have any solution, just wanted to say you can run dino as following to get english messages:  
`$LANG="en_US.UTF-8" /path/to/dino`
So you don't have to translate logs everytime

**Comment by mightyBroccoli** [comment] 2017-09-21 12:48
That is quite helpfull 🦄 thank you

**Comment by fiaxh** [comment] 2017-11-27 21:47
duplicate of #103

**Closed by fiaxh** 2017-11-27 21:47 UTC
