### ISSUE TITLE
MUC name behavior is very counter-intuitive

### ISSUE THREAD

**Issue by RalfJung** [dino/dino#871] opened 2020-07-01 18:35 UTC
I just had to have one of the devs explain to me for the second time that when Dino sees a MUC where the name is set to the local pat of the JID, it just ignores that name. That was after I desperately tried for 2 minutes to figure out why Dino ignored all my attempts to change the name to something else. I clicked almost every single pixel in the MUC settings to see if another edit field would magically appear (rather counter intuitively, the channel name etc in that window look like they cannot be edited -- until you click them; but that is a separate UI bug).

I understand you have to work with weird defaults on the server side. But the current result is very suboptimal from a UI perspective -- Dino just ignores my explicit request to name the MUC a particular way, without any indication that it is doing so.

**Comment by RalfJung** [comment] 2020-07-01 19:09
One possible option could be to show some kind of warning/info indicator when the MUC name field is in "edit mode" and is equal to the local part of the JID. Some text could show up saying "the name is equal to the local part of the JID, so Dino will instead use the names of the other participants as name for this chat".

**Comment by fiaxh** [comment] 2020-07-17 10:59
This issue is a duplicate of #758.

**Closed by fiaxh** 2020-07-17 10:59 UTC
