### ISSUE TITLE
broken build?!

### ISSUE THREAD

**Issue by albjeremias** [dino/dino#1425] opened 2023-04-18 11:37 UTC
```
/usr/include/gstreamer-1.0/gst/gstcaps.h:305:12: note: ‘_gst_reserved’ declared here
  305 |   gpointer _gst_reserved[GST_PADDING];
      |            ^~~~~~~~~~~~~
/home/user/.cache/yay/dino-git/src/dino/build/plugins/rtp/src/voice_processor.c:119:100: error: initializer element is not constant
  119 | static GstStaticPadTemplate dino_plugins_rtp_voice_processor_src_template = (GstStaticPadTemplate) {"src", GST_PAD_SRC, GST_PAD_ALWAYS, (GstStaticCaps) {NULL, "audio/x-raw,rate=48000,channels=1,layout=interleaved,format=S16LE"}};
      |                                                                                                    ^
/home/user/.cache/yay/dino-git/src/dino/build/plugins/rtp/src/voice_processor.c:119:100: note: (near initialization for ‘dino_plugins_rtp_voice_processor_src_template’)
/home/user/.cache/yay/dino-git/src/dino/build/plugins/rtp/src/voice_processor.c:119:77: error: initializer element is not constant
  119 | static GstStaticPadTemplate dino_plugins_rtp_voice_processor_src_template = (GstStaticPadTemplate) {"src", GST_PAD_SRC, GST_PAD_ALWAYS, (GstStaticCaps) {NULL, "audio/x-raw,rate=48000,channels=1,layout=interleaved,format=S16LE"}};
      |                                                                             ^
```

the dino-git is broken while building in arch the AUR
https://aur.archlinux.org/packages/dino-git

``` error: initializer element is not constant
  119 | static GstStaticPadTemplate dino_plugins_rtp_voice_processor_src_template = (GstStaticPadTemplate) {"src", GST_PAD_SRC, GST_PAD_ALWAYS, (GstStaticCaps) {NULL, "audio/x-raw,rate=48000,channels=1,layout=interleaved,format=S16LE"}};
      |                                                                                                    ^```

**Comment by mar-v-in** [comment] 2023-04-18 13:13
Duplicate of #1407

**Closed** 2024-01-13 18:52 UTC
Labels: duplicate
