### ISSUE TITLE
XEP-0174: Serverless messaging support

### ISSUE THREAD

**Issue by hhartzer** [dino/dino#1577] opened 2024-04-27 18:41 UTC
This is a finalized, but not very popular XEP. I think it seems like a neat one. Allows for offline messaging using mdns.

Is this something that Dino might be interested in?

https://xmpp.org/extensions/xep-0174.html

**Comment by sjehuda** [comment] 2024-05-22 05:02
> Is this something that Dino might be interested in?

I believe so #170 (duplicated?)

**Comment by Neustradamus** [comment] 2024-06-19 19:12
To follow this ticket.

**Comment by licaon-kter** [comment] 2024-06-19 20:00
@Neustradamus bruh, stop spamming everyone and press the d@mn "subscribe" button instead. No, I don't care about your workflow, open the browser.

**Comment by Neustradamus** [comment] 2024-06-19 20:51
@licaon-kter: I do not received messages if I do not comment on it.

**Comment by licaon-kter** [comment] 2024-06-19 21:09
@Neustradamus complain to Github, I do receive all you effing messages by some magic, and I didn't need to comment.

Star a repo, Watch it, dunno, figure it out already. 

Your doing this for years...

**Comment by sjehuda** [comment] 2024-06-19 21:15
@licaon-kter, I would argue in favour of @Neustradamus' practice, albeit
it is somewhat strange to me.

This is because, unlike the functionality "subscribe", which is not
visible to us; commenting on a ticket (even writing: +1) shows of an
interest for it.

This is especially crucial when XMPP is concerned, because of the
attempts to make people to forget about it.

**Comment by licaon-kter** [comment] 2024-06-19 21:30
The reaction emojis are exactly for that.

**Comment by fiaxh** [comment] 2024-06-20 14:29
This is a duplicate of #170.

**Closed by fiaxh** 2024-06-20 14:29 UTC
