### ISSUE TITLE
OMEMO not working on first startup

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#467] opened 2018-11-29 15:03 UTC
So I accidentally deleted my Dino directory and lost my db etc. Upon restart (542744ade258a77e6b1984c924f1398f88e5bb83), the OMEMO option was greyed out in 1to1 convos and MUCs where it did work before. Even after waiting a few minutes for the incoming messages to settle down.

After restarting Dino, it worked fine like before.

**Comment by fiaxh** [comment] 2018-11-29 17:09
Duplicate of #128.

**Closed by fiaxh** 2018-11-29 17:09 UTC
