### ISSUE TITLE
Feature request: minimize to tray

### ISSUE THREAD

**Issue by morciej** [dino/dino#956] opened 2020-12-07 20:19 UTC
We need for Dino to have an option to minimize to tray, start minimized, and quit gracefully from tray.
I use *`alltray`* for this, and it works well, but better to have the functionality built-in. Also, `alltray` has to be killed when logging out, another nuisance for newbies.

**Comment by fiaxh** [comment] 2020-12-07 20:25
This is a duplicate of #98 and #299. Running Dino in background is already experimentally possible, but tray support is not yet.
A summary of the technicalities behind trays is here https://github.com/dino/dino/issues/98#issuecomment-522249766.

**Closed by fiaxh** 2020-12-07 20:25 UTC
