### ISSUE TITLE
[Bug] Last message in conversation sidebar shows "/me" literally

### ISSUE THREAD

**Issue by bobbybee** [dino/dino#694] opened 2019-12-30 03:29 UTC
Currently the sidebar would read "Me: /me says hi", since /me transformation happens only on message display. It should read "[local alias] says hi" or something to that effect.

**Comment by fiaxh** [comment] 2019-12-30 08:15
This is a duplicate of #600.

**Closed by fiaxh** 2019-12-30 08:15 UTC
