### ISSUE TITLE
Option to accept or ignore unsercure TLS Certificates

### ISSUE THREAD

**Issue by stickybyte** [dino/dino#130] opened 2017-08-21 08:43 UTC
When using own certificates (e.g. at the company) you get the error message:

```
** (dino:27833): CRITICAL **: file /opt/dino/xmpp-vala/src/core/stanza_writer.vala: line 10: uncaught error: Unacceptable TLS certificate (g-tls-error-quark, 2)
Stream Error: TlsError in GLib: Unacceptable TLS certificate
recovering in 3
```
It's mandatory to handle this situation via options in the account overview.

**Comment by mar-v-in** [comment] 2017-08-21 08:48
Duplicate of #57.

You should nevertheless import your company or custom CA to your list of trusted authorities, so you don't have to add exceptions in every application.

_Sent from my Eterna Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2017-08-21 21:34 UTC
