### ISSUE TITLE
Conversation list has transparent blue border

### ISSUE THREAD

**Issue by BitFlipp** [dino/dino#300] opened 2018-03-02 13:40 UTC
Kernel 4.15.6-1-ARCH
Cinnamon 3.6.7 (same on Gnome Shell 3.26)
NVIDIA driver 390.25-14

Other Dino windows and non-Dino windows are not affected.
Please let me know which further information I can provide.

![conversation_list_blue_border](https://user-images.githubusercontent.com/11961313/36901287-f8df8c1c-1e26-11e8-9f5f-3e828fd85c91.png)

**Comment by philipishungry** [comment] 2018-03-05 17:08
regards the blue box happening around the main window, I have noticed it appeared on the "Render avatar on demand" (ca331e8 - 20180127) commit, at least for me, as the previous  "Small fixes to MucManager" (03a349b-20180127) I have no problem with. 
My Fedora install is fine but this happens on FreeBSD with  gtk3-3.22.15_2 installed.

**Comment by BrainBlasted** [comment] 2018-04-02 04:04
@philipishungry are you using an Nvidia GPU? I had this issue too when using nvidia.

**Comment by foucault** [comment] 2018-04-25 01:04
I noticed that the border is not visible if a non-letter avatar is displayed (ie. an actually picture). I also have an NVidia GPU.

**Comment by licaon-kter** [comment] 2018-05-10 13:31
Seeing the blue thing inside the text too. :pensive:

**Comment by BrainBlasted** [comment] 2018-05-10 20:39
Lucki, Licaon_Kter, are you both using Nvidia GPUs too? I have not seen 
this since I began using my Intel iGPU.

**Comment by Lucki** [comment] 2018-05-10 22:10
@BrainBlasted Yes, nvidia 390.48 here.
Dino is the only program showing this behavior…

…actually the problem is gone right now? I have no idea how this happened, even a restart of Dino does not bring the problem back.

**Comment by licaon-kter** [comment] 2018-05-11 06:44
@BrainBlasted yes nVidia, no composition manager.

**Comment by SinaCutie** [comment] 2018-06-03 18:29
I also get this from time to time and use an nvidia card.

Distribution: Solus 3.9999
Kernel 4.16.13-74.current
Budgie Desktop
NVIDIA driver 390.59

**Comment by Sylvhem** [comment] 2018-08-10 15:54
I'm affected too. I can see the blue border around the window and sometimes the blue lines between the text.

![A conversation with blue lines.](https://user-images.githubusercontent.com/5222316/43967441-b2ef900e-9cc4-11e8-917f-d55da7197f84.png)
![A window with blue border.](https://user-images.githubusercontent.com/5222316/43967442-b313d4fa-9cc4-11e8-8c8d-cdd183ef6474.png)

I'm using Dino 0.0~git274.ee5c838 from the openSUSE repository. My OS is Debian 9 and my DE is GNOME 3.22.2. My graphic card is a GeForce GTX 750 Ti/PCIe/SSE2 and the driver version is 384.130.

**Comment by mar-v-in** [comment] 2018-08-19 20:15
Can someone with the blue rendering issues confirm that the issue is fixed on the [avatar-image-surface branch](https://github.com/dino/dino/tree/avatar-image-surface)?

**Comment by Lucki** [comment] 2018-08-19 20:40
Sry, there's still the blue border. Not fixed here :(

**Comment by mar-v-in** [comment] 2018-08-19 20:43
@Lucki was it introduced for you with https://github.com/dino/dino/commit/ca331e85efe2a74a6b9b5a5ff0fbcd10a36758ce as well?

**Comment by Lucki** [comment] 2018-08-19 20:49
I've edited my answer. There's no blue border anymore. Are the questions still relevant?

Don't know when it was introduced. With the new commit 926056d the performance is exactly as it should be? The blue borders had a huge performance impact, which is gone now.

**Comment by mar-v-in** [comment] 2018-08-19 20:50
Great, so I guess all these nVidia related issues are fixed with that commit :tada:

**Closed** 2018-09-13 01:33 UTC
