### ISSUE TITLE
Sending a file in MUCs does not count as activity

### ISSUE THREAD

**Issue by Zash** [dino/dino#791] opened 2020-04-03 16:31 UTC
1. Find a conversation that is not the most recent one
2. Send a file, e.g. an image
3. Observe that item in the conversation list did not move to the top.

**Comment by kmq** [comment] 2020-04-18 12:09
The title change seems to imply that this issue only happens in MUCs, but from what I can tell from observation and from the code this is a problem in normal conversations as well.

The issue is that the change that triggers all signals that result in the UI update comes before the update to the data by which the List is sorted:

When a user sends a file`Conversation.last_active` is updated after the `received_file` signal is triggered (from what I understand the "received" part refers to the file being "received" by the FileManager not neccessarily having been perceived as "received" by a user). That signals starts the chain that ends up calling `invalidate_sort()` of the Gtk.ListBox which triggers the re-sort. 

Currently the last_activity property of a conversation is updated at the end of 

https://github.com/dino/dino/blob/fcad6720e66318f99940aca6b145fc50e90d29e2/libdino/src/service/file_manager.vala#L116

This issue could be resolved by moving the last_activity update to somewhere before the `received_file` signal is triggered here:

https://github.com/dino/dino/blob/fcad6720e66318f99940aca6b145fc50e90d29e2/libdino/src/service/file_manager.vala#L66

That changes the meaning of the last_activity wrt file_transfers from "after a successful file transfer" to "when a file transfer is attempted". Since that still shows as a change in the UI - the image is inserted as marked as "transfer failed" on error -  that seems ok to me.

PR available here: https://github.com/dino/dino/pull/811

**Closed** 2020-04-18 15:18 UTC
Labels: glitch, good first issue
