### ISSUE TITLE
Contact list and rooms empty

### ISSUE THREAD

**Issue by cbrchrt** [dino/dino#789] opened 2020-04-01 20:11 UTC
I'm using Dino for the first time and although I can get connected to a private server, my contact list and chat rooms are all empty.

Looking at https://github.com/dino/dino/issues/204 I got suspicious that this is a mismatch between the server and the user id. In other XMPP clients that I've tried like Pidgin, Gajim or Thunderbird, I can define a server like jabber.example and a user like user.name@example. But in Dino I am required to use user.name@jabber.example (user.name@example doesn't even connect).

I am afraid that is the problem and I have no way to change the server configuration. Is there an option in Dino to set them separately?

**Comment by mar-v-in** [comment] 2020-04-11 09:31
Is `user.name@example.tld` your JID (= the address you tell others that they should write an XMPP message to) or `user.name@jabber.example.tld`? You should always login with your JID, and if that's not possible, that is an issue (probably caused by a misconfiguration of your server).

Currently, there is no way to have a configuration in Dino that diverts from the specification like you can do in other clients. Dino can only connect if either the domain part of the JID is the actual hostname of the XMPP server or the domain part of the JID has an `xmpp-client` SRV record in its DNS pointing to the hostname of the XMPP server.

**Comment by fiaxh** [comment] 2022-01-06 18:32
There's an issue for specifying a hostname and port already, so I'll close this one as a duplicate: #115. You might want to set an SRV record pointing to `jabber.example`.

As for the seemingly empty contact list: It seems that you specified an account that Dino can't connect to, because the JID mismatches the server address. However, Dino shows the "normal" view with the left conversation list and the right part for the messages as soon as an account is enabled. Thus, it might seem like the contact list was empty, but in reality it just didn't connect.

**Closed by fiaxh** 2022-01-06 18:32 UTC
