### ISSUE TITLE
Retry when decryption failed for the first time 

### ISSUE THREAD

**Issue by donpatrice** [dino/dino#838] opened 2020-05-07 12:09 UTC
When I receive a PGP encrypted message and it fails the first time, for example I entered the wrong password three times, or a timeout, or whatever, there is no way to try decrypt a second time. It would be nice if I could trigger decryption again.

**Comment by fiaxh** [comment] 2020-05-07 12:21
This issue is a duplicate of #302.

**Closed by fiaxh** 2020-05-07 12:21 UTC
Labels: duplicate
