### ISSUE TITLE
Notification with converstation in Gnome-Shell

### ISSUE THREAD

**Issue by genofire** [dino/dino#64] opened 2017-04-27 06:10 UTC
![687474703a2f2f692e696d6775722e636f6d2f596f5a4941356f2e706e67](https://cloud.githubusercontent.com/assets/6905586/25470105/b18bb36c-2b20-11e7-8617-c2d14eaab1fe.png)
Should be supported by libnotify

**Comment by d9h02f** [comment] 2017-04-27 10:09
https://github.com/dino/dino/issues/27
https://github.com/dino/dino/issues/49

**Comment by fiaxh** [comment] 2017-08-12 09:17
Duplicate of #27

**Closed by fiaxh** 2017-08-12 09:17 UTC

**Comment by genofire** [comment] 2017-08-13 08:35
Nope, this mean also - that you could answer over the notification ...

**Comment by d9h20f** [comment] 2017-08-13 13:59
>(and has a box to reply directly from the notification)
