### ISSUE TITLE
[Feature Request] Option that changes close button to minimize instead.

### ISSUE THREAD

**Issue by xekon** [dino/dino#1134] opened 2021-11-10 07:50 UTC
I use kdocker to keep dino in the system tray. So I can click it to show dino or to hide dino to the system tray.

however if I accidentally click the close button on dino then it just closes.
An additional option in settings to change the behavior of close to minimize instead would be perfect.
Being that this is a chat application, even users without kdocker would benefit from this option so they don't close their chat.

![2021-11-09_23-50](https://user-images.githubusercontent.com/106644/141071919-16538f94-b553-4a42-937d-bc96ee4d349e.png)

**Comment by fiaxh** [comment] 2021-11-19 14:01
This is a duplicate of #299.

**Closed by fiaxh** 2021-11-19 14:01 UTC
