### ISSUE TITLE
Opt-in chat logs and encrypted in case selected

### ISSUE THREAD

**Issue by HulaHoop0** [dino/dino#953] opened 2020-12-06 16:12 UTC
Hello. Can you please disable saving conversation logs to disk by default unless opted-in by the user? (And in the case it is logged encrypt the files with a password that users can input to access it). This is of huge importance for our privacy distro usecase as in the real world logs have had a very damaging effect and are being abused to incriminate people like Assange. While projects like Adium don't care about the consequences I think you guys do.

Here is the original bug report filed by a user on our forum:

> 1) It was written that Dino prohibits to disable or purge history. I tried to use another Jabber-client on the same JID for the sensitive chats. And I tried to boot from an old snapshot which made before sensitive messages. But Dino downloads the missed history and tricks it into logs anew. I tested this on PGP chat. And I received most of the history I didn’t want to keep.
>
> All stored history is not encrypted. Physical or remote access allows to get the every chat for all time. You cannot delete no one message. Everything you write is forever in Dino.

**Comment by licaon-kter** [comment] 2020-12-06 16:42
PGP does decrypt past history, not a bug, use OMEMO if you don't want that.

Why isn't your drive encrypted?

**Comment by fiaxh** [comment] 2020-12-06 17:48
I don't think disabling chat logs by default for every user is a good idea, as it has a big negative impact on the user experience and most users will want to have (some amount of) history.
That being said, giving users an option to enable/disable logging is a valid request. We would set the default to `on`, but privacy distros could make a small patch and turn the default to `off`. This would make this issue a duplicate of #742 (with the addition to make the default easily changable for distros).

>  But Dino downloads the missed history and tricks it into logs anew. I tested this on PGP chat. And I received most of the history I didn’t want to keep.

While your user's desire for disabling logs is valid, I believe disabling logs is partially a workaround for another issue: If the user doesn't want to keep history, why is it stored on the server? I think it would be a good idea for your user to disable server-side logs.

**Comment by HulaHoop0** [comment] 2020-12-07 16:07
> Why isn't your drive encrypted?

It would be if they follow our best practices. This suggestion was for defense in depth in case they are not running in amnesiac mode.

> That being said, giving users an option to enable/disable logging is a valid request. We would set the default to on, but privacy distros could make a small patch and turn the default to off. This would make this issue a duplicate of #742 (with the addition to make the default easily changeable for distros).

@fiaxh Thanks for seeing my point. So we should advise a user to avoid servers that support the message history extension? When you implement this, can you please support configs via a drop in text file instead of compile time This would really ease the process for us. I guess we can tell Debian to change compile-time settings with the patch, but having a config mechanism would give a lot of flexibility.

**Comment by fiaxh** [comment] 2020-12-08 11:16
> So we should advise a user to avoid servers that support the message history extension?

Your user can just disable message storing for their account specifically. No need to pick a non-supporting server. This can be done in Conversations in the Account details > Archiving preferences.

> I guess we can tell Debian to change compile-time settings with the patch

No, we definitively wouldn't want *Debian* to apply that patch.

I'll close this issue as a duplicate of #742 then.

**Closed by fiaxh** 2020-12-08 11:16 UTC

**Comment by IMVIX** [comment] 2021-01-12 03:26
> If the user doesn't want to keep history, why is it stored on the server? I think it would be a good idea for your user to disable server-side logs.

It is not a issue if the server stores chats. Because these chats are encrypted. 

The problem is quite different. Gajim has such options:

<img style="float: right;" src="https://i.ibb.co/wpqDTBV/1.jpg">

But Dino has not. Dino always saves all history on servers.

For example, I run Dino from a clean snapshot with no history. Dino downloads all deleted history from the server and saves it decrypted.

And anyone who gains access (trojan or physical access, it doesn't matter) will receive my entire conversation history unencrypted. 

I can not to prevent it and to delete the part of history or the whole history.

**Comment by fiaxh** [comment] 2021-01-12 13:52
As already mentioned, I think that not storing history is a valid feature request for Dino (#742).

However in your specific case, I think it would be safest to **additionally** not store the messages on the server in first place. I was merely giving an additional security suggestion. And while I don't agree with your counter-arguments, that's okay, you don't have to follow my (unsolicited) security advice :wink:

> It is not a issue if the server stores chats. Because these chats are encrypted.

Just for the sake of completeness, here's why I don't agree with your counter-arguments: If you don't want a history of your sensitive messages to exist, it's just the safest and cleanest option to not accumulate it on the server in first place. It doesn't make sense to me that you want to keep your sensitive messages on your server and instead want to never download them.

- Even if your messages are encrypted on the server, metadata is not: The server logs contain information on who you have been writing with, at what time and how much.
- You mention the possibility of an attacker that gains access to your computer. In that case you also have to consider that this attacker gains access to your PGP key, PGP password and XMPP account credentials. Since PGP does not have forward-secrecy, the attacker can just download and decrypt your history themselves.

> Gajim has such options: [image]

The first option has been requested for Dino in #742, as already mentioned. The latter two options have been removed from Gajim one year ago ([link](https://dev.gajim.org/gajim/gajim/-/commit/30997fa1e4f4d5c656a991857f6353c07adf8966#b57eb5f0eeb1fa36c3ef037a511fec1b089bd5b1_764_761)).

> Dino always saves all history on servers

You seem to have a misconception about how server-side message history (MAM) works. Dino doesn't store your history on the server. The server directly stores all incoming and outgoing messages - independently of which clients are online or if any client actually supports MAM.

**Comment by IMVIX** [comment] 2021-01-17 17:30
>  The latter two options have been removed from Gajim one year ago

However, this is not so important. But these options are not excluded in v 1.2. And this version is the last one in Debian.

There are two really important questions.

**1. (Not)saving history on the hard drive.** Please clarify do you plan to add such settings:

* option to save or not save history on the hard drive
* option to delete one or many chats from the hard drive which were already saved

Psi and Gajim allows this. Dino saves all chats always.

**2. (Not)downloading all history after the start.** Dino downloads, decrypts and records all old chats. For example my Dino (usualy) starts on VM with zero history on the hard drive. Dino downloads all history from the server time after time. 

Server keeps this history encrypted. But Dino downloads, decrypts and stores all without of any permissions. I cannot turn this off from Dino settings.

Let's assume some variants:

* my laptop is turned on. Someone gets physical access for 5 minutes only. This person does not have the time, ability or experience to install the Trojan. But he can run Dino and just see/copy my whole history.

* my laptop is under the cameras. I can't send anything without showing the yesterday's chat.

* Etc.

P.S.

Perhaps it will be interesting to other users. I've tested Dino with Gajim and Psi. I used two JIDs, two GPG keys, two Whonix VMs with **zero history.**

* Account 1 - Gajim. Account 2 - Gajim. Gajim downloads and decrypts old messages from both accounts if the ["server message archive"](https://camo.githubusercontent.com/b56ef7c1d4f121c6a7f94f6351aa8aff6d972667d345cf677f2f6a9e85447c42/68747470733a2f2f692e6962622e636f2f777071445442562f312e6a7067) setting is enabled. Gajim does not load anything if this setting is disabled.

* Account 1 - Gajim. Account 2 - Dino. Dino downloads and decrypts all old messages. Including the messages which were sent from Account#1 by Gajim. It doesn't matter if the "server message archive" is enabled of disabled (in Gajim).

* Account  1 - Psi. Account 2 - Dino. Psi does not load messages. They have announced a $ 1,500 bounty for the MOM tweak. But I don't see the final result yet ([#62](https://github.com/psi-im/psi/issues/62), [#618](https://github.com/psi-plus/main/issues/618)).

* Account 1 - first Psi and then Dino. Account 2 - Gajim/Dino/Psi. Dino (1) downloads all old messages. But Dino (1) **cannot decrypt** the old messages which were sent from the same account (1) by Psi before. Dino (1) decrypts only messages from Account 1 which sent Dino (1) before. And all messaged from Account 2.

**Comment by licaon-kter** [comment] 2021-01-17 18:23
>  But he can run Dino and just see/copy my whole history.
>  two GPG keys

Umm,seems strange to use encryption that enables history, and complain that the client downloads... history.

OMEMO does not allow re-decryption of messages, fyi.

**Comment by IMVIX** [comment] 2021-01-17 21:48
> Umm, seems strange to use encryption that enables history, and complain that the client downloads... history.

Gajim, Psi, Conversations allows to disable (1) savind chats on the hard drive and (2) disable downloading history. I do not understand Dino's plans about issues (1) and (2). Therefore I asked about it.

> OMEMO does not allow re-decryption of messages, fyi.

Yes, I know. But my questions were not about OMEMO.

Dino cannot re-decrypt OMEMO-history. But Dino always downloads it. Messages, time, senders, recepients are visible. On the other hand Dino has an issue with OMEMO when VM loads from clean shapshot with zero history. I think you understand me.

**Comment by S0yf00d-exe** [comment] 2022-06-05 19:00
User choice option feature to **Disable Local Logging** not just chats but also files and avatars.
