### ISSUE TITLE
Add option to purge local chat history

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#656] opened 2019-11-21 19:45 UTC
Sometimes I feel I don't need the tons of chat history of a MUC or in another chat I ain't need old conversations anymore. Therefor it would be convenient to be able to purge a chat history like in Conversations for example.

**Comment by fiaxh** [comment] 2019-11-22 16:11
This is a duplicate of #472.

**Closed by fiaxh** 2019-11-22 16:11 UTC
