### ISSUE TITLE
Link to Conference Details in menu_conversation named "Contact Details"

### ISSUE THREAD

**Issue by Ppjet6** [dino/dino#268] opened 2018-01-09 23:25 UTC
## Steps to reproduce

- Join conference
- Click on the top-left menu, where the item "Contact Details" is.

## What happens

This links to a windows named "Conference Details".

## What I expect

The link should probably be named "Conference Details" as well.
I can see in the code why it's the way it is. The same view is used for both conference and chat. This might be a bit confusing though.

**Comment by fiaxh** [comment] 2018-01-09 23:42
Duplicate of #182

**Closed by fiaxh** 2018-01-09 23:42 UTC
