### ISSUE TITLE
Last message correction: Don't display corrected message as individual ones

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#663] opened 2019-11-26 16:07 UTC
Currently if one receives a long message and the original author find's several mistakes and corrects them one after another, it ends up having the same (long) message several times in the chat -- each version with a tiny change.

It would be very convenient in my eyes to only display the last version but also to have an option, maybe a small button next to the message, which opens a list view of the former versions.

This would make the last message correction much more pleasant in my eyes.

**Comment by fiaxh** [comment] 2019-11-26 16:08
This is a duplicate of #272.

**Closed by fiaxh** 2019-11-26 16:08 UTC
