### ISSUE TITLE
Suggest emojis when using the colon syntax

### ISSUE THREAD

**Issue by MaybeThisIsRu** [dino/dino#1027] opened 2021-03-30 15:28 UTC
Emoji autocompletion has already been tackled in https://github.com/dino/dino/issues/395, although not yet merged.

My feature request is an extension of it. When I type `:emoji_name`, I would like fuzzy search to kick in and make a keyboard navigable dropdown of matching emojis.

A video demonstration of this feature in Signal Desktop [is available on Imgur](https://i.imgur.com/1vGBHcb.mp4).

**Comment by hirusi** [comment] 2021-03-31 04:52
Ah, I see this has been raised in the discussion: https://github.com/dino/dino/pull/689#pullrequestreview-337747293. Please feel free to close if that feels right.

**Comment by fiaxh** [comment] 2024-01-13 18:50
I'll close this a a duplicate of #395, because I see auto-completion as a necessary part of it, as explained in the discussion linked above.

**Closed by fiaxh** 2024-01-13 18:50 UTC
