### ISSUE TITLE
Show MUC name instead of MUC JID in roster

### ISSUE THREAD

**Issue by silberzwiebel** [dino/dino#21] opened 2017-03-17 10:13 UTC
in particular since Conversations creates arbitrary digits/letters (I do not understand why, but ok), it makes it hard to grasp what the MUC is actually about when the topic is not shown in the roster.

**Comment by iNPUTmice** [comment] 2017-03-17 12:02
FWIW Conversations will - at some point - switch to displaying the name of the MUC.

**Comment by ge0rg** [comment] 2017-03-23 16:51
Yes, please use the identity name from disco#info according to https://xmpp.org/extensions/xep-0045.html#disco-roominfo

It's not set on some MUCs that exist right now, but it's the best field for this matter.

**Comment by d9h20f** [comment] 2017-08-22 16:58
The title in the Headerbar should also be the other way around: now the JID is on top, large and bold, with the title below, but this should be reversed.

**Comment by schiessle** [comment] 2018-05-13 08:56
I have a slightly different feature request here #360. Please let me repeat my ideas here, as my ticket was closed as a duplicate of this one.

The MUC name discussed here comes from the server and is not changeable per user/client, right? Then it is not exactly what I'm looking for at #360. Also with Conversation (Which was mentioned as a example) I have the problem that the MUC name is often longer then the space available to display it, e.g. for IRC chats (which I bridge to XMPP with Biboumi) it uses the topic which can be quite long and often isn't really useful to identify the room. This looks strange and makes it often hard to identify the right room. Also if someone decides to change the topic, the room name changes which is highly irritating.

With Gajim I can set room aliases which defines the name of the room in the rooster. This is really useful because it allows me to name the many rooms I have in a way that makes it easy for me to find the right room quickly. I would be happy if there would be a similar option for Dino (and Conversation, but that's out of scope here :wink: )

**Comment by weiss** [comment] 2018-09-26 12:17
I agree with @schiessle.  I'd use the bookmark's `name` attribute, which XEP-0048 defines as [the friendly name by which bookmarks will be displayed in the client][1].  This could be made editable in the contact details just like the roster name is editable for 1:1 contacts, so the UI/UX would be consistent.  I'd use the room name (the one controlled by room owners) as a fallback in case the user didn't set a bookmark name.

[1]: https://xmpp.org/extensions/xep-0048.html#format

**Comment by fiaxh** [comment] 2018-11-02 15:44
After 1e54a44 and ddd17e7, Dino now makes use of the MUC name (controlled by the owners) if one is available.

**Closed** 2019-12-24 14:17 UTC
Labels: ✨ UI
