### ISSUE TITLE
Can´t see messages I seend myself via omemo

### ISSUE THREAD

**Issue by theScrabi** [dino/dino#621] opened 2019-10-04 08:50 UTC
When I'm trying to send a OMEMO encrypted message to my self from Conversation, so I can receive it on Dino, Dino simply shows me:
```
I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo
```
However I scanned my key from Dino, and I Accepted my key from Conversation.

When I'm trying to send a OMEMO message from Dino to Conversation, the message is correctly received on the Conversation site, however on Dino I immediately receive a message saying  `[This message is OMEMO encrypted]`:

![Bildschirmfoto vom 2019-10-04 10-32-10](https://user-images.githubusercontent.com/1891273/66194400-aa67fa00-e694-11e9-8e26-e82457317632.png)

The messages from the green C are sent by Conversations.

![Screenshot_20191004-103522_Conversations](https://user-images.githubusercontent.com/1891273/66194443-c10e5100-e694-11e9-9ab3-81b0bb8342fc.png)
The messages with the red D are sent by Dino.

**Comment by licaon-kter** [comment] 2019-10-04 09:01
Dino from HEAD? What version?

**Comment by theScrabi** [comment] 2019-10-04 09:35
0.0-0.13.20190917.git.f746ce7.fc30
fedora repoitory

**Comment by licaon-kter** [comment] 2019-10-04 10:15
There is a fix on HEAD for unverified keys, if you look at your account in Dino, for your other devices....are they verified or not? If not... update from HEAD and retest.

**Comment by theScrabi** [comment] 2019-10-04 10:53
Both my smarthphone and my Dino key is listed, however I have two more devices besides my phone and my laptop. On my phone are its own and 3 more associated keys installed, two of these keys are not installed on dino as dino so far only knows my phone.

However the phone key is set verified in dino (the red box):
![Bildschirmfoto vom 2019-10-04 12-45-59](https://user-images.githubusercontent.com/1891273/66202382-ec4d6c00-e6a5-11e9-8fd0-ab801a764dea.png)
![Bildschirmfoto vom 2019-10-04 12-46-59](https://user-images.githubusercontent.com/1891273/66202384-ece60280-e6a5-11e9-9401-a6246e446f96.png)

**Comment by theScrabi** [comment] 2019-10-04 12:27
Yes on HEAD i can revive messages and be able to send them :)
However I am still seeing the message `[This message is OMEMO encrypted]` when I send something from dino:
![grafik](https://user-images.githubusercontent.com/1891273/66207436-1194a700-e6b3-11e9-8eb2-b218d72f1a11.png)

**Comment by fiaxh** [comment] 2019-10-04 20:10
This is a duplicate of #591.

**Closed by fiaxh** 2019-10-04 20:10 UTC
