### ISSUE TITLE
Removing a contact should be unodable (or warn)

### ISSUE THREAD

**Issue by RalfJung** [dino/dino#882] opened 2020-07-14 21:10 UTC
Usually, deleting something is an action that can either be undone again or has a warning that it cannot be undone. But I just accidentally deleted a contact from my contact list in the Dino "Start conversation" window when I tried to figure out what the "-" button does. That button has no tooltip (also a great way to make a GUI explain itself), so I figured nothing too bad would happen when I press it. I was somewhat surprised to see that it just deleted the contact without any warning or an obvious way to undo what I did.

**Comment by fiaxh** [comment] 2020-07-17 10:57
This issue is a duplicate of #81.

**Closed by fiaxh** 2020-07-17 10:57 UTC
