### ISSUE TITLE
omemo should use 12-byte IVs

### ISSUE THREAD

**Issue by moparisthebest** [dino/dino#265] opened 2018-01-06 04:47 UTC
Refer to [Conversations #2578](https://github.com/siacs/Conversations/issues/2578) for all the nitty gritty details.

The code that needs changed in dino is [here](https://github.com/dino/dino/blob/master/plugins/omemo/src/stream_module.vala#L48).

The annoying part is, since not all clients are updated yet, the code needs to support *reading* both 12 AND 16 byte IVs for the near future, and probably still continue sending 16-byte ones until some point in the future.

Conversations and gajim support reading both, and I think both of them still send 16-bytes as of now.  I need to check with chatsecure again...

Let me know if you have any questions.

**Comment by chrisballinger** [comment] 2018-01-06 18:30
I don't think we support 12-byte IVs yet. Thanks for the heads up!

**Comment by foss-** [comment] 2019-01-28 14:46
just another data point: this is also a problem when communicating between monal and dino clients: https://github.com/anurodhp/Monal/issues/187

**Comment by selurvedu** [comment] 2019-06-07 08:39
I am still not able to send or receive OMEMO encrypted messages to and from Pidgin + Lurch, all I see is `[This message is OMEMO encrypted]` – both when receiving a message sent from Dino to Pidgin and vice versa. Any other combination of clients (Gajim, Conversations, Pidgin + Lurch) behave correctly. This problem persists since 2017.

**Comment by Neustradamus** [comment] 2020-02-17 13:39
2 years after this ticket (not the more old), Conversations project has been officially switched to 12 (like other softwares/librairies).

Can you update the Dino OMEMO code?

Thanks in advance.

Linked to:
- https://github.com/xsf/xeps/pull/894

**Comment by DanScharon** [comment] 2020-04-22 11:48
at the moment Monal users can't read OMEMO encrypted messages from Dino. That's really unfortunate

**Comment by Neustradamus** [comment] 2020-04-22 11:54
@DanScharon: Not only, all major XMPP client have switched from 16 to 12 now.

**Comment by DanScharon** [comment] 2020-04-22 11:55
@Neustradamus yeah, but most still accept 16, Monal doesn't

**Comment by Neustradamus** [comment] 2020-04-22 12:00
@DanScharon: The problem is not Monal, it is that "some" XMPP clients have not changed.
You can see that it is not a new ticket, the problem/information was here... Badly...
Time to change of XMPP client...

**Comment by tmolitor-stud-tu** [comment] 2020-04-22 12:23
The thing was: old omemo initially used 12 bytes, but was later upgraded to use 16 byte (https://xmpp.org/extensions/xep-0384.html#protocol-message_encryption step 3)

The upgrade path that developers agreed upon was:
- add read support for 16 byte IV to all clients but still send and read 12 byte IVs
- once all clients can read 16 byte IVs start sending 16 byte IVs but still accept 12 byte IVs
- once all users updated their clients drop support for reading 12 byte IVs

Monal can only read/write 12 byte IVs due to some librrary/legal restrictions in france.
Conversations can read both and currently writes 12 byte IVs

**Comment by tmolitor-stud-tu** [comment] 2020-04-22 12:42
**Sorry, my fault. I initially confused 16 and 12 byte IVs, but now the correct story:**

Old omemo initially used 16 bytes, but was later upgraded to use 12 byte
The upgrade path that developers agreed upon was:

-  add read support for 12 byte IV to all clients but still send and read 16 byte IVs
- once all clients can read 12 byte IVs start sending 12 byte IVs but still accept 16 byte IVs
- once all users updated their clients drop support for reading 16 byte IVs

Monal can only read/write 12 byte IVs due to some library/legal restrictions in france.
Conversations can read both, but I'm not sure what it is writing right now.

**Comment by Neustradamus** [comment] 2020-04-22 12:58
@tmolitor-stud-tu: Yes it is this... Dino does not send with 12.

**Comment by Neustradamus** [comment] 2020-04-22 12:59
@tmolitor-stud-tu: Yes it is this... Dino does not send with 12, always 16.

I had done a ticket (closed badly) here:
- https://github.com/dino/dino/issues/749

**Comment by mar-v-in** [comment] 2020-04-22 13:08
@Neustradamus You are misrepresenting the facts.

The plan was indeed the three phases as @tmolitor-stud-tu described. However, before the second phase was actually reached, Monal decided to not only start sending 12-byte IV, but also stop support for reading 16-byte IV, which means Monal jumped straight from phase 1 to phase 3.
Enforcing 12-byte IV is not and never was standards compliant. The pull request by the Monal developer to change the standard such that they can blame others for not being standards compliant (xsf/xeps#894) was not accepted as part of the XSF standardization process. Therefor Monal enforcing 12-byte IV is the misbehavior, not Dino sending 16-byte IVs.

Since OMEMO 0.4.0, 16-byte IVs are enforced by the standard (see https://xmpp.org/extensions/attic/xep-0384-0.4.0.html#protocol-message_encryption), however it also included a namespace bump. As Monal did the change without a namespace bump, it is not possible to be compatible with Monal and an OMEMO 0.3.0 compliant 16-byte IV client at the same time.

Dino will eventually move to send 12-byte IVs. However, we will stick to the original plan. Until recently the Dino version in Ubuntu LTS that was installed by a significant number of users did not support reading 12-byte IVs (as it is from early 2018). Luckily this got updated, so the plan is to start the second phase and send 12-byte IV with the next release.

**Comment by Neustradamus** [comment] 2020-04-22 13:09
@Echolon, @mar-v-in: Do not mix this big bug and OMEMO > 0.3.0.
It must be solved before the new 0.5.0 support.

**Comment by Neustradamus** [comment] 2020-04-22 13:28
@Echolon, @mar-v-in: Monal does not support OMEMO 0.5.0 it is for this that there are not the namespace.

The XSF badly has not created a XEP-0384 v0.3.1 with the missing point ;)

**Comment by Neustradamus** [comment] 2020-08-30 22:43
Any news on it?

**Comment by PilzAdam** [comment] 2020-09-15 14:43
Should be fixed by cd5b639a826ccafe5741a51f10cc8ca76ebfdd14.

**Closed** 2020-09-15 14:49 UTC
Labels: 🐠 OMEMO

**Comment by Neustradamus** [comment] 2020-09-15 23:29
+ this commit: https://github.com/dino/dino/commit/1956f63179c4f3ac3232cc4a2da8046565fad2a1

Solve an issue after previous commit: https://github.com/dino/dino/issues/909

**Comment by schmittlauch** [comment] 2020-10-14 23:47
What is the schedule for a next release? The 0.2.0 milestone is currently empty.

As someone who converses with Monal users, I am currently building Dino from source – which works totally fine thanks to NixOS. But I see the need for other users getting this change as well as soon as possible.

Thanks for your work so far.

**Comment by Neustradamus** [comment] 2020-11-12 22:51
To all, good news of the day!

Thanks to @Dino devs, it is now solved in the new build: Dino 0.2.0:
- https://dino.im/blog/2020/11/dino-0.2-release/

Recall about commits:
- https://github.com/dino/dino/commit/cd5b639a826ccafe5741a51f10cc8ca76ebfdd14
- https://github.com/dino/dino/commit/1956f63179c4f3ac3232cc4a2da8046565fad2a1

After a very long time, since:
- 7th August 2017: "non-standard aes-gcm IV length": https://github.com/iNPUTmice/Conversations/issues/2578
- 6th January 2018 (This ticket): "omemo should use 12-byte IVs": https://github.com/dino/dino/issues/265

Big thanks to the launcher: @moparisthebest.

**Comment by Neustradamus** [comment] 2021-01-02 20:15
Note: There is a 0.1 branch with 2 fixes which have been added in 0.2.0:
- 0.1 branch: https://github.com/dino/dino/commits/v0.1
- The Dino 0.1.1 release (12 Nov 2020): https://github.com/dino/dino/releases/tag/v0.1.1
- https://github.com/dino/dino/commit/7bb4e4ef62bf2e967b8368531e2eb1e5b0481947 in 0.1.x = https://github.com/dino/dino/commit/cd5b639a826ccafe5741a51f10cc8ca76ebfdd14 in 0.2.0
- https://github.com/dino/dino/commit/d6d4e5eb0a8c69240c1bb56486806e7c7c90457c in 0.1.x = https://github.com/dino/dino/commit/1956f63179c4f3ac3232cc4a2da8046565fad2a1 in 0.2.0
