### ISSUE TITLE
Can't select multiline text

### ISSUE THREAD

**Issue by gjedeer** [dino/dino#874] opened 2020-07-07 14:18 UTC
dino 0.1.0~git99.20200610.50c55c7, ubuntu 18.04 x86_64

How to reproduce: try copying text from more than 1 message. It's not possible to highlight the text of more than 1 message.

**Comment by fiaxh** [comment] 2020-07-07 14:20
This is a duplicate of #85.

**Closed by fiaxh** 2020-07-07 14:20 UTC
