### ISSUE TITLE
XmlError in stanza_reader.vala

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#678] opened 2019-12-18 15:15 UTC
Strange XML error: https://gist.githubusercontent.com/stevenroose/5faa38373e66876411757eb6c36ba350/raw/0965e8792111ebd3db7c833ce622b4180bf735f7/xmlerror.xml

**Comment by mar-v-in** [comment] 2019-12-23 19:52
The XML error is caused by the stream being closed by the server or a network change (as you can see directly after the strange errors) and that happened in the middle of a stanza being send (so the stanza couldn't be parsed completely). The error looks strange because the stanza itself contains the vCard (which you can see as it was the thing requested right before) and vCards include a base64 encoded picture (so what you see printed there is actually a part of the base64 encoded picture inside the vCard).

While it looks strange, it is not relevant and nothing that can be fixed.

**Closed by mar-v-in** 2019-12-23 19:52 UTC
