### ISSUE TITLE
[OSX] building issue with libsoup

### ISSUE THREAD

**Issue by novia713** [dino/dino#735] opened 2020-02-01 09:42 UTC
i'm trying to build Dino on macos 10.15.1 and i'm getting this
```
leandro at profident in ~/git/dino (master)
$ ./configure
-- Found Make: /usr/bin/make
--   Running with make. Using Ninja (ninja-build) might improve build experience.
-- Configuring Dino 0.1.0 with plugins: http-files, omemo, openpgp
-- ALPN support enabled
-- Configuring done
CMake Error in plugins/http-files/CMakeLists.txt:
  Imported target "libsoup-2.4" includes non-existent path

    "/usr/include/libxml2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Comment by stephanlukasczyk** [comment] 2020-02-05 11:30
I can confirm this, having the exact same issue. Besides that, the home-brew formula mentioned in the [wiki](https://github.com/dino/dino/wiki/macOS) seems to be gone.

**Comment by novia713** [comment] 2020-02-05 12:19
yes, the brew formula is no more available, it fails :-/

**Comment by licaon-kter** [comment] 2020-03-11 10:43
I've updated the [build instructions](https://github.com/dino/dino/wiki/macOS) but then still fails with this error. :(

**Comment by mar-v-in** [comment] 2020-03-24 15:04
This can be fixed by just installing libxml2 via `brew install libxml2`. I updated the wiki page accordingly.

**Comment by stephanlukasczyk** [comment] 2020-03-25 12:28
Works with the updated instructions, thanks @mar-v-in !

**Closed** 2020-05-07 13:22 UTC
Labels: 🍏 macOS, 🏗 Build
