### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by lhirlimann** [dino/dino#488] opened 2019-01-02 09:57 UTC
./configure
make
[ 94%] Building C object plugins/omemo/CMakeFiles/omemo.dir/src/account_settings_widget.c.o
[ 94%] Building C object plugins/omemo/CMakeFiles/omemo.dir/src/bundle.c.o
[ 95%] Building C object plugins/omemo/CMakeFiles/omemo.dir/src/contact_details_provider.c.o
[ 95%] Building C object plugins/omemo/CMakeFiles/omemo.dir/src/contact_details_dialog.c.o
/home/ludovic/Documents/src/dino/build/plugins/omemo/src/contact_details_dialog.c:16:10: fatal error: qrencode.h: No such file or directory
 #include "qrencode.h"
          ^~~~~~~~~~~~
compilation terminated.
make[3]: *** [plugins/omemo/CMakeFiles/omemo.dir/build.make:232: plugins/omemo/CMakeFiles/omemo.dir/src/contact_details_dialog.c.o] Error 1
make[3]: Leaving directory '/home/ludovic/Documents/src/dino/build'
make[2]: *** [CMakeFiles/Makefile2:753: plugins/omemo/CMakeFiles/omemo.dir/all] Error 2
make[2]: Leaving directory '/home/ludovic/Documents/src/dino/build'
make[1]: *** [Makefile:130: all] Error 2
make[1]: Leaving directory '/home/ludovic/Documents/src/dino/build'
make: *** [Makefile:2: default] Error 2

Are we missing some dependencies.

**Comment by jubalh** [comment] 2019-01-02 10:05
Obviously you are:

```
No such file or directory
#include "qrencode.h"
```

**Comment by lhirlimann** [comment] 2019-01-02 10:12
Indeed. Question is why isn't that detected by ./configure ?

**Comment by fiaxh** [comment] 2019-01-02 14:18
Duplicate of #454.

**Closed by fiaxh** 2019-01-02 14:18 UTC
