### ISSUE TITLE
Add support for message retractions

### ISSUE THREAD

**Issue by pravi** [dino/dino#1291] opened 2022-10-17 14:02 UTC
This is required for spam cleanups in public mucs. gajim already implements this (there is an xep too).

**Comment by licaon-kter** [comment] 2022-10-17 14:08
https://xmpp.org/extensions/xep-0424.html ?

Siskin has this

**Comment by fiaxh** [comment] 2022-10-28 09:55
This is a duplicate of #1133.

**Closed by fiaxh** 2022-10-28 09:55 UTC
