### ISSUE TITLE
feature request: when posting images should request to compress them

### ISSUE THREAD

**Issue by albjeremias** [dino/dino#1322] opened 2022-12-01 14:44 UTC
Yeah, when I post a picture by copy/paste or uploading, would be cool if dino requests to compress the picture before sending, would help a loads of people with accessiblity and slow internet connections. so it's a very important feature in terms of inclusivity :)

**Comment by fiaxh** [comment] 2023-01-27 21:59
This is a duplicate of #1280.

**Closed by fiaxh** 2023-01-27 21:59 UTC
