### ISSUE TITLE
Report: used master, then 0.1.0-4 from Arch, then master: OMEMO broken

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#839] opened 2020-05-08 16:20 UTC
So I couldn't compile Dino anymore for some time and I started using the stock Dino on Arch.

Then after 2 weeks or so, I managed to compile Dino again and I used master again.

I noticed that OMEMO was broken. People were no longer encrypting for me OMEMO key, while my outgoing messages were valid for Conversations.

My OMEMO key is also not shown in the Accounts display:
![screenshot-2020-05-08-17-23-32](https://user-images.githubusercontent.com/853468/81425853-3a50b380-9150-11ea-859e-1a76244df47f.png)

I got this debug log for `libdino,OMEMO`:
```
(dino:723725): libdino-DEBUG: 17:19:23.913: connection_manager.vala:159: [steven@konuro.net] New connection with resource dino.93a626a6: 0x560450cbee90
(dino:723725): libdino-DEBUG: 17:19:23.916: message_processor.vala:53: MAM: [steven@konuro.net] Reset catchup_id
(dino:723725): libdino-DEBUG: 17:19:25.957: message_processor.vala:112: MAM: [steven@konuro.net] MAM available
(dino:723725): libdino-DEBUG: 17:19:25.957: message_processor.vala:138: MAM: [steven@konuro.net] Start catchup
(dino:723725): libdino-DEBUG: 17:19:25.958: message_processor.vala:155: MAM: [steven@konuro.net] Previous entry exists
(dino:723725): libdino-DEBUG: 17:19:25.958: message_processor.vala:228: MAM: [steven@konuro.net] Get range  - 
(dino:723725): libdino-DEBUG: 17:19:49.398: message_processor.vala:471: MAM: [steven@konuro.net] Hitted range duplicate message id. id 9a4dacb2-1f4b-4fbc-ada3-eb991bc7bdcd qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.404: message_processor.vala:436: MAM: [steven@konuro.net] Hitted range duplicate server id. id 1588954251338826 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.410: message_processor.vala:436: MAM: [steven@konuro.net] Hitted range duplicate server id. id 1588954261997739 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.416: message_processor.vala:471: MAM: [steven@konuro.net] Hitted range duplicate message id. id e4876462-270b-477a-88cd-0f1fa380bd5e qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.421: message_processor.vala:471: MAM: [steven@konuro.net] Hitted range duplicate message id. id 70b35dfc-0b93-4a27-be44-aed7957c9ba1 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.427: message_processor.vala:471: MAM: [steven@konuro.net] Hitted range duplicate message id. id 9df00c00-a8fe-482b-b696-b0582746344b qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.434: message_processor.vala:471: MAM: [steven@konuro.net] Hitted range duplicate message id. id 229e72fb-3cf7-4260-9c74-4943681c0f29 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.440: message_processor.vala:436: MAM: [steven@konuro.net] Hitted range duplicate server id. id 1588954347412504 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.446: message_processor.vala:471: MAM: [steven@konuro.net] Hitted range duplicate message id. id 7c53f3fd-76d9-43c6-b71a-64e671a0a0f0 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.451: message_processor.vala:436: MAM: [steven@konuro.net] Hitted range duplicate server id. id 1588954362094633 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.455: message_processor.vala:471: MAM: [steven@konuro.net] Hitted range duplicate message id. id 1dc0d306-8dbf-422d-8c2e-92a0a0cc6e26 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.464: message_processor.vala:436: MAM: [steven@konuro.net] Hitted range duplicate server id. id 1588954391207186 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.469: message_processor.vala:436: MAM: [steven@konuro.net] Hitted range duplicate server id. id 1588954465266206 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.474: message_processor.vala:436: MAM: [steven@konuro.net] Hitted range duplicate server id. id 1588954511357986 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.483: message_processor.vala:436: MAM: [steven@konuro.net] Hitted range duplicate server id. id 1588954513822331 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.492: message_processor.vala:471: MAM: [steven@konuro.net] Hitted range duplicate message id. id 5d556407-4519-4e68-8b2e-2e196ec1f5d0 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.498: message_processor.vala:436: MAM: [steven@konuro.net] Hitted range duplicate server id. id 1588954540117077 qid 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.501: message_processor.vala:248: MAM: [steven@konuro.net] Update from_id 1588954245573338
(dino:723725): libdino-DEBUG: 17:19:49.501: message_processor.vala:250: MAM: [steven@konuro.net] We get our first MAM page
(dino:723725): libdino-DEBUG: 17:19:49.512: message_processor.vala:285: MAM: [steven@konuro.net] Hitted contains key 31f17b29-a7af-4b7a-a98d-417c238091b0
(dino:723725): libdino-DEBUG: 17:19:49.513: message_processor.vala:209: MAM: [steven@konuro.net] Merging 0-1588953467 with 1588954245- 1588954540
(dino:723725): libdino-DEBUG: 17:20:49.037: connection_manager.vala:184: [steven@konuro.net 0x560450cbee90] Error: GLib.IOError: Error receiving data: Connection reset by peer
(dino:723725): libdino-DEBUG: 17:20:49.049: connection_manager.vala:205: [steven@konuro.net] Check reconnect in 5 sec

(dino:723725): xmpp-vala-CRITICAL **: 17:20:54.048: file /home/steven/software/dino/xmpp-vala/src/core/xmpp_stream.vala: line 124: uncaught error: IOError in GLib: Error writing data to TLS socket: The specified session has been invalidated for some reason. (xmpp-io-stream-error-quark, 1)
(dino:723725): libdino-DEBUG: 17:21:04.047: connection_manager.vala:239: [steven@konuro.net 0x560450cbee90] Ping timeouted. Reconnecting
(dino:723725): libdino-DEBUG: 17:21:04.059: connection_manager.vala:159: [steven@konuro.net] New connection with resource dino.93a626a6: 0x56045505f0e0
(dino:723725): libdino-DEBUG: 17:21:04.068: message_processor.vala:53: MAM: [steven@konuro.net] Reset catchup_id
(dino:723725): libdino-DEBUG: 17:21:04.075: connection_manager.vala:246: Error disconnecting stream: IOError in GLib: Error writing data to TLS socket: The specified session has been invalidated for some reason.
```

**Comment by fiaxh** [comment] 2020-05-09 18:14
This has been discussed in the public channel. The problem wasn't on Dino's site but caused by misplaced binaries. Closing.

**Closed by fiaxh** 2020-05-09 18:14 UTC

**Comment by stevenroose** [comment] 2020-05-10 09:07
I moved the binary away from the `.so` files, which broke the plugins.
