### ISSUE TITLE
No nicks in MUCs

### ISSUE THREAD

**Issue by elimohl** [dino/dino#598] opened 2019-08-15 16:42 UTC
I cannot see nicks in some MUCs. Instead a conference name is show for every user.

Checked for a fresh dino version from github, dino-im (0.0.git20190718.1853ee8-2) from the debian sid repository and for dino 0.0~git497.3ad2891 from http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/Debian_Next

**Comment by licaon-kter** [comment] 2019-08-15 16:47
Type of MUC? Public? Private? OMEMO?

**Comment by mar-v-in** [comment] 2019-08-15 18:05
This is a known bug that happens after you received an invite for that room. a fix is in the making

**Comment by sonnyp** [comment] 2019-09-11 16:04
I'm being affected by this issue, could you share the state of the bug fix? I'd be happy to have a look if you did not have time so far in which case a direction would be appreciated.

**Comment by Mikaela** [comment] 2019-09-15 16:40
I think this is a duplicate of https://github.com/dino/dino/issues/431, but with more discussion.

I think I accidentally caused this for one MUC by first attempting to add it as a contact, closing it after noticing my mistake and then joining it properly.

Debian Testing, Dino c8f2b80 (?)

**Closed** 2019-10-18 19:25 UTC
