### ISSUE TITLE
Empty password?

### ISSUE THREAD

**Issue by JulienPalard** [dino/dino#1333] opened 2023-01-03 09:10 UTC
I'm on dino 0.3.1 from Debian packages.

I'm trying to register an account (server is an ejabberd): it does not work, I'm getting:

> The password contains unacceptable characters

while my test password only contains ASCII characters.

So here I am debugging with `dino-im --print-xmpp=all`, and I see I'm sending an empty password:

```xml
XMPP OUT [chapril.org stream:0x55e6dcc482d0 thread:0x55e6d9f01890 2023-01-03T09:48:07+0100]
<iq id='4412e0b6-6289-47a1-9bc0-171e42a379a3' type='set' to='chapril.org'>
  <query xmlns='jabber:iq:register'>
    <x type='submit' xmlns='jabber:x:data'>
      <instructions>
        Choose a username and password to register with this server
      </instructions>
      <field var='FORM_TYPE' type='hidden'>
        <value>
          jabber:iq:register
        </value>
      </field>
      <field var='username' type='text-single' label='User'>
        <required />
        <value>
          mdk.fr
        </value>
      </field>
      <field var='password' type='text-private' label='Password'>
        <required />
        <value>
          
        </value>
```

The server answer contains:

```
  <error type='modify'>
    <not-acceptable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas' />
    <text lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>
      The password contains unacceptable characters
    </text>
  </error>
```

It does not looks like an error with the server though, as I'm able to create the exact same account using pidgin.

Here I don't know if it's a privacy measure to not display the password while logging it to stdout (I haven't found such a measure in the code), or if there's a bug in dino making it not send my password?

**Comment by fiaxh** [comment] 2023-01-07 23:02
I can't reproduce this - I registered an account with chapril.org just fine.

> Here I don't know if it's a privacy measure to not display the password while logging it to stdout (I haven't found such a measure in the code), or if there's a bug in dino making it not send my password?

This is not a security feature, that's actually what is being sent. For some reason, the password isn't included. However, since it works for me, there seems to be an additional factor at work.

**Comment by fiaxh** [comment] 2024-09-22 16:46
Since I can't reproduce this and have no further information, I'm going to close this.
If you can give me further details (e.g. whether that happens with every password or just specific ones or whether you can always reproduce it or whether it only happens on this server), that help me reproduce this issue, we can of course reopen it.

**Closed by fiaxh** 2024-09-22 16:46 UTC
