### ISSUE TITLE
Feature: Unread message indicator

### ISSUE THREAD

**Issue by 143981** [dino/dino#1326] opened 2022-12-15 15:51 UTC
Like this:
![mQluRgQeGYAeujgBX72ckNE6u4PDKd3p](https://user-images.githubusercontent.com/106692737/207905988-15f6c00e-6c98-4870-b251-0383603444d9.png)

This is really need without tray icon with indicator...

**Comment by fiaxh** [comment] 2023-01-08 00:13
This looks like a duplicate of #144.

**Closed by fiaxh** 2023-01-08 00:13 UTC
