### ISSUE TITLE
If MUCs requires membership to sent messages, display a hint / disable input field

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#719] opened 2020-01-16 10:08 UTC
Join `xmpp:kuketzblog@rooms.dismail.de?join` with Dino as a non-member and write something: Your message will end up in the nirvana without further notice.

If you try the same with Conversations, you'll notice that Conversations disables the input field, which additional contains a hint "You are not a member".

The reason is, that there are MUCs which allow only members to send messages in order to mitigate spam.

Dino should handle this case properly.

**Comment by fiaxh** [comment] 2020-01-18 14:49
This is a duplicate of #582.

**Closed by fiaxh** 2020-01-18 14:49 UTC
