### ISSUE TITLE
Crash due to markup parsing error

### ISSUE THREAD

**Issue by Shungy** [dino/dino#915] opened 2020-09-21 01:31 UTC
Dino crashes when receiving or sending a certain message. Opening the conversation that has that specific message also crashes Dino. 

Error log:

```
string_slice: assertion '_tmp3_' failed                                    
string_slice: assertion '_tmp2_' failed                                    
string_slice: assertion '_tmp2_' failed                                    
dino_ui_util_parse_add_markup: assertion 's_ != NULL' failed               
string_slice: assertion '_tmp3_' failed                                    
string_slice: assertion '_tmp2_' failed                                    
string_slice: assertion '_tmp2_' failed                                    
dino_ui_util_parse_add_markup: assertion 's_ != NULL' failed               
string_slice: assertion '_tmp3_' failed                                    
string_slice: assertion '_tmp2_' failed                                    
string_slice: assertion '_tmp2_' failed                                    
dino_ui_util_parse_add_markup: assertion 's_ != NULL' failed               
string_slice: assertion '_tmp3_' failed                                    
string_slice: assertion '_tmp2_' failed                                    
string_slice: assertion '_tmp2_' failed                                    
dino_ui_util_parse_add_markup: assertion 's_ != NULL' failed
```

**To replicate** (1) run the command below to copy the problematic message into your clipboard, (2) open a conversation in Dino, (3) Ctrl+V to paste the message, (4) Press enter, dino is dead. Just join to the same conversation to crash it as much as you want. If the conversation with this message is the first one in Dino, running the program will be impossible.

```
echo -en '\x49\x20\x66\x6f\x75\x6e\x64\x20\x6f\x75\x72\x20\x63\x6f\x6e\x76\x65\x72\x73\x61\x74\x69\x6f\x6e\x20\x77\x68\x65\x72\x65\x20\x49\x20\x64\x65\x73\x63\x72\x69\x62\x65\x64\x20\x76\x6f\x6c\x75\x6e\x74\x61\x72\x79\x20\x70\x69\x6c\x6f\x65\x72\x65\x63\x74\x69\x6f\x6e\x20\x61\x6e\x64\x20\x74\x68\x65\x20\x63\x6f\x6e\x6e\x65\x63\x74\x69\x6f\x6e\x20\x74\x6f\x20\x73\x61\x64\x69\x73\x6d\x20\x69\x6e\x20\x6d\x65\x20\x62\x65\x66\x6f\x72\x65\x20\x49\x20\x6b\x6e\x65\x77\x20\x74\x68\x65\x20\x74\x65\x72\x6d\x2e\x20\x49\x74\x20\x69\x73\x20\x66\x72\x6f\x6d\x20\x32\x30\x32\x30\x2d\x30\x34\x2d\x30\x38\x3a\x0a\x3e\x20\x49\x20\x73\x74\x61\x72\x74\x65\x64\x20\x63\x6f\x6e\x73\x63\x69\x6f\x75\x73\x6c\x79\x20\x74\x68\x69\x6e\x6b\x69\x6e\x67\x20\x6f\x66\x20\x73\x61\x64\x69\x73\x74\x69\x63\x20\x66\x61\x6e\x74\x61\x73\x69\x65\x73\x20\x2a\x66\x6f\x72\x2a\x20\x70\x6c\x65\x61\x73\x75\x72\x65\x2e' | xclip -sel clipboard
```

I used hex code of the message because copying and pasting to the browser might make some changes to the formatting. I could not figure out the exact issue with the message so this is as short as I can get.

**Comment by Shungy** [comment] 2020-09-21 12:08
Send the message to chat@dino.im for maximum casualties XD
People won’t be able to open Dino until they remove the message from the database file.

**Comment by fiaxh** [comment] 2020-09-21 12:48
I can't reproduce this. What version of Dino are you using?

**Comment by Shungy** [comment] 2020-09-21 15:39
> What version of Dino are you using?
0.1.0
Specifically dino-0.1.0-2.fc32.src.rpm

**Comment by eerielili** [comment] 2023-11-07 20:02
can't reproduce, should be closed i think

**Comment by fiaxh** [comment] 2024-01-13 18:31
If someone encounters this issue again, I'd be interested in details. Until then I'll close this issue, assuming it is outdated.

**Closed by fiaxh** 2024-01-13 18:31 UTC
Labels: bug
